// web/src/lib/components/BaseModal.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	import { fade } from 'svelte/transition';
	export let show;

	const dispatch = createEventDispatcher();
</script>


{#if show}
	<div
		on:click|self={() => dispatch('close')}
		class="background"
		transition:fade="{{ duration: 100 }}"
	>
		<div class="body">
			<slot />
		</div>
	</div>
{/if}


<style lang="scss">
	.background {
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
		background-color: rgba(0, 0, 0, 0.5);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;

		.body {
			background-color: $bg-medium;
			border: 1px solid $bg-light;
			padding: 0.25rem 1.25rem;
		}
	}
</style>

// src/client/components/BaseModal.vue
<script>
export default {
	props: {
		show: {
			type: Boolean,
			default: false,
		},
	},
	emits: ['close'],
};
</script>

<template>
	<teleport to="body">
		<transition name="fade" mode="out-in">
			<div
					v-if="show"
					class="modal"
					@click.self="this.$emit('close')"
					>
					<section class="modal-body">
						<slot />
					</section>
			</div>
		</transition>
	</teleport>
</template>

<style scoped lang="sass">
.modal
	position: absolute
	top: 0
	right: 0
	bottom: 0
	left: 0
	background-color: rgba(0, 0, 0, 0.5)
	display: flex
	flex-direction: column
	align-items: center
	justify-content: center

.modal-body
	background-color: $bg-medium
	border: 1px solid $bg-light
	padding: 1.25rem

	& > :first-child
		margin-top: 0
	& > :last-child
		margin-bottom: 0
</style>
