// web/src/lib/components/BattlesnakeRooms.svelte
<script>
	export let rooms;
</script>

<table>
	<thead>
		<tr>
			<th>Room</th>
			<th>Players</th>
			<th>Password</th>
		</tr>
	</thead>

	<tbody>
		{#each rooms as room (room.id)}
			<tr class="clickable">
				<a class="delink" href="/games/battlesnake/{room.id}">
					<td>
						<p class="big">{room.name}</p>
					</td>

					<td>
						<ul>
							{#each room.players as player (player.id)}
								<li>{player.username}</li>
							{/each}
						</ul>
					</td>

					<td>
						{#if room.hasPassword}
							<i class="fas fa-check fa-3x" />
						{:else}
							<i class="fas fa-times fa-3x" />
						{/if}
					</td>
				</a>
			</tr>
		{/each}
	</tbody>
</table>


<style lang="scss">
	table {
		text-align: center;
		width: 100%;
		border-spacing: 0;
		border: 0.1rem solid $fg-medium;
		margin: 0.5rem 0 2.5rem 0;
		thead {
			background: $fg-medium;
			font-size: 1.5rem;
			tr {
				display: flex;
				th {
					font-weight: normal;
					padding: 0.5rem 0;
					flex: 1;
				}
			}
		}

		tbody tr {
			background-color: $bg-dark;
			&:nth-child(even) {
				background-color: $bg-medium;
			}

			a {
				display: flex;
				align-items: center;

				td {
					flex: 1;

					.big {
						font-size: 1.25rem;
					}

					ul {
						margin: 1rem 0;
						padding: 0;
						li {
							list-style-type: none;
						}
					}
				}
			}
		}
	}
</style>

// src/client/components/games/BattlesnakeRooms.vue
<script>
import BattlesnakeRoomsItem from './BattlesnakeRoomsItem.vue';

export default {
	components: {
		BattlesnakeRoomsItem,
	},
	async created() {
		if (this.$store.state.battlesnakeRooms.length <= 0) {
			try {
				const data = await fetch('/api/battlesnake/rooms');
				const rooms = await data.json();
				this.$store.commit('setBattlesnakeRooms', rooms);
			} catch (err) {
				console.error(err);
			};
		};
	},
};
</script>

<template>
	<section>
		<table>
			<thead>
				<tr>
					<td>Room</td>
					<td>Players</td>
					<td>Password</td>
				</tr>
			</thead>
			<tbody>
				<BattlesnakeRoomsItem
						v-for="(room, index) in this.$store.state.battlesnakeRooms"
						:key="index"
						:name="room.name"
						:roomID="room.id"
						:players="room.players"
						:hasPassword="room.password ? 'Yes' : 'No'"
						/>
			</tbody>
		</table>
	</section>
</template>

<style scoped lang="sass">
table
	text-align: center
	width: 100%
	border-spacing: 0
	border: 0.1rem solid $fg-medium

thead
	background: $fg-medium
	font-size: 1.5rem
	tr
		display: flex
	td
		padding: 0.5rem 0
		flex: 1
</style>
