// client/src/components/Navbar.vue
<script>
import NavbarItem from './NavbarItem.vue';

export default {
	components: {
		NavbarItem,
	},
	props: {
		navItems: {
			type: Array,
			required: true,
		},
	},
};
</script>

<template>
	<nav>
		<ul>
			<NavbarItem
					v-for="(item, index) in navItems"
					:to="item.path"
					:key="index"
					>
					{{ item.title }}
			</NavbarItem>
		</ul>
	</nav>
</template>

<style scoped lang="sass">
ul
	margin: 0.5rem 0
	padding: 0
	list-style-type: none
	display: flex
	background-color: $bg-medium
</style>

// client/src/lib/components/Navbar.svelte
<script>
	export let routes;
</script>

<nav>
	<ul class="delist row">
		{#each routes as route}
			<li>
				<a class="delink" href={route.path}>{route.title}</a>
			</li>
		{/each}
	</ul>
</nav>

<style lang="scss">
	nav ul {
		margin: 0.5rem 0;
		background-color: $bg-medium;

		li a {
			display: block;
			padding: 0.5rem 1rem;
			font-style: bold;
			font-size: 1.1rem;
			transition: background-color 0.05s;

			&:hover {
				background-color: $fg-medium;
			}
			&:active {
				background-color: $fg-dark;
			}
		}
	}
</style>
