// client/components/BaseModal.vue
<script setup>
import { defineProps, defineEmits } from '@nuxtjs/composition-api'
const props = defineProps({
	show: {
		type: Boolean,
		default: false,
	},
});
const emit = defineEmits(['close']);
</script>

<template>
	<Transition name="fade" mode="out-in">
		<div
				v-if="show"
				class="modal-background"
				@click.self="emit('close')"
				>
				<div class="modal-body">
					<slot />
				</div>
		</div>
	</Transition>
</template>

<style scoped lang="scss">
.modal-background {
	position: fixed;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	background-color: rgba(0, 0, 0, 0.5);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;

	.modal-body {
		background-color: $bg-medium;
		border: 1px solid $bg-light;
		padding: 1.25rem;

		& > :first-child {
			margin-top: 0;
		}
		& > :last-child {
			margin-bottom: 0;
		}
	}
}
</style>

// web/src/lib/components/BaseModal.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	import { fade } from 'svelte/transition';
	export let show;

	const dispatch = createEventDispatcher();
</script>


{#if show}
	<div
		on:click|self={() => dispatch('close')}
		class="background"
		transition:fade="{{ duration: 100 }}"
	>
		<div class="body">
			<slot />
		</div>
	</div>
{/if}


<style lang="scss">
	.background {
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
		background-color: rgba(0, 0, 0, 0.5);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;

		.body {
			background-color: $bg-medium;
			border: 1px solid $bg-light;
			padding: 0.25rem 1.25rem;
		}
	}
</style>
